### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by ogada-otieno** [kodi-ke/client#6]
TODO

- [x] contains app's icon
- [x] conditionals for tenant, landlord, and will integrate for manager later
- [x] landlord: Dashbord, My Properties, Requests, Issues, Notification bell, User image
- [x] tenant: Dashbord, Payments, Requests, Raise an Issue, Notification bell, User image
- [x] Without Auth: Check Figma
Check Figma for additional details

**Comment by oyieroyier** [comment]
Initial iteration of Navbar components for Mobile, Desktop and Tablet devices complete.
